version: '3.3'
services:
  mongodb:
    image: 'docker.io/mongo'
    container_name: test-mongo-db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
